const formatCurrency = (amount) => {
  return (Number(amount) || 0).toLocaleString("en-IN", {
    style: "currency",
    currency: "INR",
  });
};

const formatDate = (dateString) => {
  if (!dateString) return "-";
  return new Date(dateString).toLocaleDateString("en-IN");
};

const getBaseStyle = () => `
  @page { margin: 15mm; size: A4 portrait; }
  body {
    font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
    color: #333;
    margin: 0;
    padding: 0;
    font-size: 11px;
    -webkit-print-color-adjust: exact;
  }
  .header {
    text-align: center;
    margin-bottom: 20px;
    border-bottom: 2px solid #1976d2;
    padding-bottom: 10px;
  }
  .shop-name { font-size: 24px; font-weight: 800; color: #1976d2; margin: 0; text-transform: uppercase; letter-spacing: 1px; }
  .report-title { font-size: 16px; font-weight: 600; margin: 5px 0 0 0; color: #555; }
  .report-meta { font-size: 12px; color: #777; margin-top: 5px; }
  
  table { width: 100%; border-collapse: collapse; margin-top: 15px; page-break-inside: auto; }
  tr { page-break-inside: avoid; page-break-after: auto; }
  th { background-color: #f5f5f5; color: #333; font-weight: 700; text-align: left; padding: 10px 8px; border-bottom: 2px solid #ddd; }
  td { padding: 8px; border-bottom: 1px solid #eee; color: #444; }
  
  .text-right { text-align: right; }
  .text-center { text-align: center; }
  .font-bold { font-weight: bold; }
  .text-success { color: #2e7d32; }
  .text-danger { color: #d32f2f; }
  .text-primary { color: #1976d2; }
  
  .summary-box { display: flex; justify-content: space-between; margin-bottom: 20px; gap: 15px; }
  .summary-card { flex: 1; padding: 15px; background: #f9fafb; border: 1px solid #e0e0e0; border-radius: 6px; }
  .summary-label { font-size: 10px; color: #666; text-transform: uppercase; font-weight: 600; margin-bottom: 5px; }
  .summary-value { font-size: 18px; font-weight: 800; color: #111; }
  
  .footer { text-align: center; margin-top: 30px; font-size: 9px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
`;

const renderHeader = (title, period, shopName = "KOSH BUSINESS") => `
  <div class="header">
    <h1 class="shop-name">${shopName}</h1>
    <h2 class="report-title">${title}</h2>
    ${period ? `<div class="report-meta">Period: ${formatDate(period.start)} to ${formatDate(period.end)}</div>` : ""}
  </div>
`;

const renderFooter = () => `
  <div class="footer">
    Generated by Kosh Business Software • ${new Date().toLocaleString("en-IN")}
  </div>
`;

module.exports = {
  generatePnLTemplate: (data, period, shopName) => {
    return `
      <!DOCTYPE html><html><head><style>${getBaseStyle()}</style></head><body>
      ${renderHeader("Profit & Loss Statement", period, shopName)}
      
      <div class="summary-box">
        <div class="summary-card">
          <div class="summary-label">Total Revenue</div>
          <div class="summary-value text-success">${formatCurrency(data.totalRevenue)}</div>
        </div>
        <div class="summary-card">
          <div class="summary-label">COGS</div>
          <div class="summary-value text-danger">${formatCurrency(data.totalCogs)}</div>
        </div>
        <div class="summary-card">
          <div class="summary-label">Gross Profit</div>
          <div class="summary-value text-primary">${formatCurrency(data.grossProfit)}</div>
        </div>
        <div class="summary-card">
          <div class="summary-label">Net Profit</div>
          <div class="summary-value ${data.netProfit >= 0 ? "text-success" : "text-danger"}">${formatCurrency(data.netProfit)}</div>
        </div>
      </div>

      <h3 style="margin-top: 20px; font-size: 14px; border-bottom: 1px solid #ddd; padding-bottom: 5px;">Operating Expenses Breakdown</h3>
      <table>
        <thead><tr><th>Expense Category</th><th class="text-right">Amount</th></tr></thead>
        <tbody>
          ${data.expenses.length === 0 ? '<tr><td colspan="2" class="text-center">No expenses recorded</td></tr>' : ""}
          ${data.expenses
            .map(
              (e) => `
            <tr><td>${e.category}</td><td class="text-right text-danger">${formatCurrency(e.total)}</td></tr>
          `,
            )
            .join("")}
          <tr style="background-color: #fefefe;">
            <td class="font-bold">Total Operating Expenses</td>
            <td class="text-right font-bold">${formatCurrency(data.totalExpenses)}</td>
          </tr>
        </tbody>
      </table>
      ${renderFooter()}
      </body></html>
    `;
  },

  generateLedgerTemplate: (data, title, entityName, period, shopName) => {
    return `
      <!DOCTYPE html><html><head><style>${getBaseStyle()}</style></head><body>
      ${renderHeader(`${title}: ${entityName}`, period, shopName)}
      
      <div class="summary-box" style="justify-content: flex-start;">
        <div class="summary-card" style="flex: none; width: 200px;">
          <div class="summary-label">Opening Balance</div>
          <div class="summary-value">${formatCurrency(data.openingBalance)}</div>
        </div>
        <div class="summary-card" style="flex: none; width: 200px;">
          <div class="summary-label">Closing Balance</div>
          <div class="summary-value font-bold ${data.closingBalance > 0 ? "text-danger" : "text-success"}">
            ${formatCurrency(data.closingBalance)}
          </div>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Type</th>
            <th>Ref / Note</th>
            <th class="text-right">Debit / Inflow (+)</th>
            <th class="text-right">Credit / Outflow (-)</th>
            <th class="text-right">Balance</th>
          </tr>
        </thead>
        <tbody>
          <tr style="background: #f9f9f9;">
            <td colspan="5" class="text-right"><em>Opening Balance</em></td>
            <td class="text-right font-bold">${formatCurrency(data.openingBalance)}</td>
          </tr>
          ${data.transactions.length === 0 ? '<tr><td colspan="6" class="text-center">No transactions</td></tr>' : ""}
          ${data.transactions
            .map(
              (t) => `
            <tr>
              <td>${formatDate(t.date)}</td>
              <td><span style="background: #eee; padding: 2px 6px; border-radius: 4px; font-size: 9px;">${t.record_type}</span></td>
              <td>
                <div class="font-bold">${t.reference_no}</div>
                ${t.note ? `<div style="font-size: 9px; color: #888;">${t.note}</div>` : ""}
              </td>
              <td class="text-right ${t.debit || t.inflow ? "font-bold" : ""}">${formatCurrency(t.debit || t.inflow || 0)}</td>
              <td class="text-right ${t.credit || t.outflow ? "font-bold" : ""}">${formatCurrency(t.credit || t.outflow || 0)}</td>
              <td class="text-right font-bold">${formatCurrency(t.balance)}</td>
            </tr>
          `,
            )
            .join("")}
        </tbody>
      </table>
      ${renderFooter()}
      </body></html>
    `;
  },

  generateStockSummaryTemplate: (data, period, shopName) => {
    return `
      <!DOCTYPE html><html><head><style>${getBaseStyle()}</style></head><body>
      ${renderHeader("Stock Movement Summary", period, shopName)}
      
      <table>
        <thead>
          <tr>
            <th>Product</th>
            <th class="text-right">Opening</th>
            <th class="text-right text-primary">In (+)</th>
            <th class="text-right text-danger">Out (-)</th>
            <th class="text-right">Adj (+/-)</th>
            <th class="text-right">Net Change</th>
            <th class="text-right">Closing</th>
          </tr>
        </thead>
        <tbody>
          ${data.records.length === 0 ? '<tr><td colspan="7" class="text-center">No data found</td></tr>' : ""}
          ${data.records
            .map(
              (r) => `
            <tr>
              <td class="font-bold">${r.product_name}</td>
              <td class="text-right">${r.opening_qty}</td>
              <td class="text-right text-primary">${r.purchased_qty || "-"}</td>
              <td class="text-right text-danger">${r.sold_qty || "-"}</td>
              <td class="text-right">${r.adjusted_qty || "-"}</td>
              <td class="text-right font-bold ${r.net_change > 0 ? "text-success" : r.net_change < 0 ? "text-danger" : ""}">
                ${r.net_change > 0 ? "+" : ""}${r.net_change}
              </td>
              <td class="text-right font-bold" style="font-size: 13px;">${r.closing_qty}</td>
            </tr>
          `,
            )
            .join("")}
        </tbody>
      </table>
      ${renderFooter()}
      </body></html>
    `;
  },

  generateStockValuationTemplate: (data, shopName) => {
    return `
      <!DOCTYPE html><html><head><style>${getBaseStyle()}</style></head><body>
      ${renderHeader("Inventory Valuation Report", null, shopName)}
      
      <div class="summary-box" style="justify-content: center; margin-top: 40px;">
        <div class="summary-card" style="text-align: center;">
          <div class="summary-label">Master Stock Valuation</div>
          <div class="summary-value text-primary" style="font-size: 24px;">${formatCurrency(data.masterValuation)}</div>
          <div class="report-meta" style="margin-top: 10px;">Calculated using Product Master Quantities × Average Purchase Price</div>
        </div>
        <div class="summary-card" style="text-align: center;">
          <div class="summary-label">Batch-wise Valuation</div>
          <div class="summary-value text-success" style="font-size: 24px;">${formatCurrency(data.batchValuation)}</div>
          <div class="report-meta" style="margin-top: 10px;">Calculated using active Batch Quantities × Batch Cost</div>
        </div>
      </div>
      ${renderFooter()}
      </body></html>
    `;
  },
};
