import { z } from "zod";

export const productSchema = z.object({
  name: z.string().min(1, "Name is required"),
  // Product code can be generated by backend if categories are new
  product_code: z.string().optional(),
  hsn: z.string().optional(),
  gst_rate: z.number().min(0, "GST rate must be non-negative"),
  mrp: z.number().min(0, "MRP must be non-negative"),
  mop: z.number().min(0, "MOP must be non-negative").optional(),

  // ✅ ALLOW STRING (New Name) OR NUMBER (Existing ID)
  category: z.union([z.number(), z.string()]).optional(),
  subcategory: z.union([z.number(), z.string()]).optional(),

  storage_location: z.string().optional(),
  quantity: z.number().min(0, "Quantity must be non-negative"), // Removed .int() to allow float

  // ✅ UNIT CONVERSION FIELDS
  base_unit: z.string().default("pcs"),
  secondary_unit: z.string().optional().nullable(),
  conversion_factor: z.number().default(1),

  description: z.string().optional().nullable(),
  brand: z.string().optional().nullable(),
  barcode: z.string().optional().nullable(),
  image_url: z.string().optional().nullable(),
  is_active: z.number().int().optional(),
  average_purchase_price: z.number().optional(),
  mfw_price: z.string().optional().nullable(),
  low_stock_threshold: z.number().optional().nullable(),
  size: z.string().optional().nullable(),
  weight: z.string().optional().nullable(),
  tracking_type: z.enum(["none", "batch", "serial"]).optional().default("none"),
});
