import {
  LayoutDashboard,
  ScanBarcode,
  BarChart3,
  FileText,
  ChartCandlestick,
  FileClock,
  Truck,
  ClipboardList,
  Boxes,
  SquareStack,
  ArchiveRestore,
  ArchiveX,
  IndianRupee,
  BookA,
  User,
  UserSearch,
  Notebook,
  Users,
  ShieldCheck,
  Settings,
  Clock,
  Search,
  BookAlert,
  Clipboard,
  ClipboardCheck,
  UsersRound,
  BookCheck,
  CloudCheck,
  Printer,
  MessageSquare,
  Send,
} from "lucide-react";
import { MenuSection } from "../lib/navigation";

export const menuSections: MenuSection[] = [
  {
    title: "Dashboards",
    hotkey: "D",
    items: [
      {
        label: "Business Dashboard",
        icon: <LayoutDashboard size={20} />,
        path: "/dashboard",
        hotkey: "B",
      },
      {
        label: "Accounting Dashboard",
        icon: <BookCheck size={20} />,
        path: "/accounting",
        hotkey: "A",
      },
    ],
  },
  {
    title: "Sales Vouchers",
    hotkey: "S",
    items: [
      {
        label: "Sales Voucher (POS)",
        icon: <ScanBarcode size={20} />,
        path: "/billing",
        hotkey: "V",
      },
      {
        label: "Sales Register",
        icon: <Clock size={20} />,
        path: "/sales-history",
        hotkey: "R",
      },
      {
        label: "Sales Dashboard",
        icon: <BarChart3 size={20} />,
        path: "/sales",
        hotkey: "D",
      },
      {
        label: "Quotations Register",
        icon: <FileText size={20} />,
        path: "/quotations",
        hotkey: "Q",
      },
      {
        label: "Sales Orders List",
        icon: <ClipboardCheck size={20} />,
        path: "/sales-order-list",
        hotkey: "L",
      },
      {
        label: "Generate Sales Order",
        icon: <Clipboard size={20} />,
        path: "/sales-order",
        hotkey: "G",
      },
    ],
  },
  {
    title: "Purchase Vouchers",
    hotkey: "P",
    items: [
      {
        label: "Purchase Voucher",
        icon: <FileText size={20} />,
        path: "/purchase",
        hotkey: "V",
      },
      {
        label: "Purchase Register",
        icon: <FileClock size={20} />,
        path: "/purchase-history",
        hotkey: "R",
      },
      {
        label: "Purchase Dashboard",
        icon: <ChartCandlestick size={20} />,
        path: "/purchase-dashboard",
        hotkey: "D",
      },
    ],
  },
  {
    title: "Inventory Books",
    hotkey: "I",
    items: [
      {
        label: "Stock Register",
        icon: <Boxes size={20} />,
        path: "/products",
        hotkey: "R",
      },
      {
        label: "Stock Summary",
        icon: <ClipboardList size={20} />,
        path: "/inventory",
        hotkey: "M",
      },
      {
        label: "Stock Adjustments",
        icon: <Boxes size={20} />,
        path: "/adjustments",
        hotkey: "J",
      },
      {
        label: "Stock Groups",
        icon: <SquareStack size={20} />,
        path: "/categories",
        hotkey: "G",
      },
      {
        label: "Batch/Serial Tracker",
        icon: <Search size={20} />,
        path: "/tracker",
        hotkey: "X",
      },
      {
        label: "Stock Reorder Advice",
        icon: <ArchiveRestore size={20} />,
        path: "/stock-restock",
        hotkey: "O",
      },
      {
        label: "Dead Stock Analysis",
        icon: <ArchiveX size={20} />,
        path: "/dead-stock",
        hotkey: "Z",
      },
      {
        label: "Stock ABC Analysis",
        icon: <ChartCandlestick size={20} />,
        path: "/product-abc-page",
        hotkey: "B",
      },
    ],
  },
  {
    title: "Accounting Vouchers",
    hotkey: "A",
    items: [
      {
        label: "Payment Register",
        icon: <IndianRupee size={20} />,
        path: "/transactions",
        hotkey: "R",
      },
      {
        label: "Day Book",
        icon: <BookA size={20} />,
        path: "/daybook",
        hotkey: "K",
      },
      {
        label: "Journal / Expenses",
        icon: <FileText size={20} />,
        path: "/expenses",
        hotkey: "J",
      },
    ],
  },
  {
    title: "Party Ledgers",
    hotkey: "C",
    items: [
      {
        label: "Customer Register",
        icon: <User size={20} />,
        path: "/customers",
        hotkey: "C",
      },
      {
        label: "Supplier Register",
        icon: <Truck size={20} />,
        path: "/suppliers",
        hotkey: "S",
      },
      {
        label: "Customer Dashboard",
        icon: <UserSearch size={20} />,
        path: "/customer-analytics",
        hotkey: "D",
      },
      {
        label: "Outstandings Register",
        icon: <BookAlert size={20} />,
        path: "/customers/accounts",
        hotkey: "O",
      },
    ],
  },
  {
    title: "Statutory Reports",
    hotkey: "R",
    items: [
      {
        label: "GST Reports",
        icon: <Notebook size={20} />,
        path: "/gst",
        hotkey: "G",
      },
      {
        label: "Access Logs",
        icon: <ShieldCheck size={20} />,
        path: "/access-logs",
        hotkey: "L",
      },
      {
        label: "Employees",
        icon: <UsersRound size={20} />,
        path: "/employees",
        hotkey: "E",
      },
      {
        label: "User Management",
        icon: <Users size={20} />,
        path: "/users",
        hotkey: "M",
      },
    ],
  },
  {
    title: "Settings & Tally",
    hotkey: "T",
    items: [
      {
        label: "Settings",
        icon: <Settings size={20} />,
        path: "/settings",
        hotkey: "S",
      },
      {
        label: "Tally Sync",
        icon: <CloudCheck size={20} />,
        path: "/tally",
        hotkey: "Y",
      },
      {
        label: "Tally Config",
        icon: <Settings size={20} />,
        path: "/tally-config",
        hotkey: "F",
      },
      {
        label: "Kosh Business",
        icon: <CloudCheck size={20} />,
        path: "/business-settings",
        hotkey: "K",
      },
    ],
  },
  {
    title: "WhatsApp",
    hotkey: "W",
    items: [
      {
        label: "WhatsApp Hub",
        icon: <MessageSquare size={20} />,
        path: "/whatsapp",
        hotkey: "H",
      },
      {
        label: "Messaging Hub",
        icon: <Send size={20} />,
        path: "/messaging",
        hotkey: "M",
      },
      {
        label: "Usage & Billing Log",
        icon: <BarChart3 size={20} />,
        path: "/whatsapp/analytics",
        hotkey: "B",
      },
    ],
  },
  {
    title: "Utilities",
    hotkey: "U",
    items: [
      {
        label: "Cheque Printing",
        icon: <Printer size={20} />,
        path: "/cheque-printing",
        hotkey: "P",
      },
    ],
  },
];
